name = input("Your name? ")
city = input("Where do you live? ")
age = input("How old are you? ")
print(f"Hello! My name is {name}, i live in {city}, i'm {age} years old.")
num1 = input("Whrite the 1st number: ")
num2 = input("Write the 2nd number: ")
print(num1)
print(num2)
print("Summ num1 + num2 = ", int(num1) + int(num2))